# Setup screens for 16 notebook sessions
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=0 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_1/ --port 8800"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=1 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_2/ --port 8801"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=2 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_3/ --port 8802"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=3 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_4/ --port 8803"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=4 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_5/ --port 8804"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=5 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_6/ --port 8805"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=6 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_7/ --port 8806"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=7 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_8/ --port 8807"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=8 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_9/ --port 8808"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=9 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_10/ --port 8809"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=10 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_11/ --port 8810"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=11 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_12/ --port 8811"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=12 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_13/ --port 8812"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=13 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_14/ --port 8813"
screen -dm bash -c "source activate tensorflow_p36;CUDA_VISIBLE_DEVICES=14 jupyter notebook /home/ubuntu/dis_jan_2019_notebooks/team_15/ --port 8814"
